### ISSUE TITLE
Current state and to-do

### ISSUE THREAD

**Issue by mrcaseb** [leesharpe/nflseedR#1]
I'll try to summarize what I have done and what's next. I might change this or add stuff if I forget something.

## Done

- Initialized package environment and most of the dependencies
- added helper scripts to data-raw
- add a data frame containing divisions and documented it
- made the tiebreaker constants available in `sysdata.R`
- added MIT license (we can change that @leesharpe)
- put division, conference and draft functions in separate scripts
- added new exported function that computes division ranks `R/compute_division_ranks.R`. I changed the argument name from `debug` to `.debug` as the former is a `base` function. Also had to add some arguments to the underlying functions.
- ran the tidyverse styler to apply tidyverse code style guide. 

## To-Do

- [x] Do analogue things for seeds and draft order like the above mentioned div ranks functions
- [x] Add global functions that wraps everything and does the simulation?
- [x] Document exported functions
- [x] Update Readme
- [x] pkgdown website? If yes, add a vignette with examples and a hex logo

I am pretty sure I forgot stuff but that's all for now.

@leesharpe please feel free to look at what I have done, ask if something is unclear and modify if necessary.

**Comment by mrcaseb** [comment]
Dumping this here in case we need it at some point. 

I made some benchmarks to try to figure out the best performance of `simulate_nfl` in parallel processes. I think it depends on the number of available cores so here's the code for the test. The reprex runs with 50 seasons because otherwise it's awful long but I ran my tests with 1000 seasons as well. 

It looks like we get optimal performance if the number of rounds results in half of the available cores. So that's my new default value of sims_per_round.

```r
library(nflseedR)
library(microbenchmark)
set.seed(4)

seasons <- 500
mbm <- microbenchmark(
  single_round =  simulate_nfl(2020, fresh_season = TRUE, simulations = seasons, sims_per_round = seasons),
  quarter_cores = simulate_nfl(2020, fresh_season = TRUE, simulations = seasons, sims_per_round = seasons / future::availableCores() * 4),
  half_cores    = simulate_nfl(2020, fresh_season = TRUE, simulations = seasons, sims_per_round = seasons / future::availableCores() * 2),
  full_cores    = simulate_nfl(2020, fresh_season = TRUE, simulations = seasons, sims_per_round = seasons / future::availableCores() * 1),
  times = 5
  )
#> * 2021-02-15 12:23:34: Loading games data
#> * 2021-02-15 12:23:35: Beginning simulation of 500 seasons in 4 rounds
#> * 2021-02-15 12:24:06: Combining simulation data
#> * 2021-02-15 12:24:08: Aggregating across simulations
#> * 2021-02-15 12:24:08: Loading games data
#> * 2021-02-15 12:24:08: Beginning simulation of 500 seasons in 4 rounds
#> * 2021-02-15 12:24:34: Combining simulation data
#> * 2021-02-15 12:24:35: Aggregating across simulations
#> * 2021-02-15 12:24:35: Loading games data
#> * 2021-02-15 12:24:35: Beginning simulation of 500 seasons in 4 rounds
#> * 2021-02-15 12:25:02: Combining simulation data
#> * 2021-02-15 12:25:02: Aggregating across simulations
#> * 2021-02-15 12:25:02: Loading games data
#> * 2021-02-15 12:25:03: Beginning simulation of 500 seasons in 4 rounds
#> * 2021-02-15 12:25:29: Combining simulation data
#> * 2021-02-15 12:25:31: Aggregating across simulations
#> * 2021-02-15 12:25:31: Loading games data
#> * 2021-02-15 12:25:31: Beginning simulation of 500 seasons in 8 rounds
#> * 2021-02-15 12:25:58: Combining simulation data
#> * 2021-02-15 12:26:00: Aggregating across simulations
#> * 2021-02-15 12:26:00: Loading games data
#> * 2021-02-15 12:26:00: Beginning simulation of 500 seasons in 2 rounds
#> * 2021-02-15 12:26:31: Combining simulation data
#> * 2021-02-15 12:26:32: Aggregating across simulations
#> * 2021-02-15 12:26:32: Loading games data
#> * 2021-02-15 12:26:32: Beginning simulation of 500 seasons in 2 rounds
#> * 2021-02-15 12:27:02: Combining simulation data
#> * 2021-02-15 12:27:02: Aggregating across simulations
#> * 2021-02-15 12:27:03: Loading games data
#> * 2021-02-15 12:27:03: Beginning simulation of 500 seasons in 1 round
#> * 2021-02-15 12:27:48: Combining simulation data
#> * 2021-02-15 12:27:49: Aggregating across simulations
#> * 2021-02-15 12:27:49: Loading games data
#> * 2021-02-15 12:27:49: Beginning simulation of 500 seasons in 2 rounds
#> * 2021-02-15 12:28:19: Combining simulation data
#> * 2021-02-15 12:28:20: Aggregating across simulations
#> * 2021-02-15 12:28:20: Loading games data
#> * 2021-02-15 12:28:20: Beginning simulation of 500 seasons in 4 rounds
#> * 2021-02-15 12:28:47: Combining simulation data
#> * 2021-02-15 12:28:49: Aggregating across simulations
#> * 2021-02-15 12:28:49: Loading games data
#> * 2021-02-15 12:28:49: Beginning simulation of 500 seasons in 8 rounds
#> * 2021-02-15 12:29:16: Combining simulation data
#> * 2021-02-15 12:29:17: Aggregating across simulations
#> * 2021-02-15 12:29:17: Loading games data
#> * 2021-02-15 12:29:18: Beginning simulation of 500 seasons in 2 rounds
#> * 2021-02-15 12:29:47: Combining simulation data
#> * 2021-02-15 12:29:48: Aggregating across simulations
#> * 2021-02-15 12:29:48: Loading games data
#> * 2021-02-15 12:29:48: Beginning simulation of 500 seasons in 2 rounds
#> * 2021-02-15 12:30:18: Combining simulation data
#> * 2021-02-15 12:30:19: Aggregating across simulations
#> * 2021-02-15 12:30:19: Loading games data
#> * 2021-02-15 12:30:20: Beginning simulation of 500 seasons in 1 round
#> * 2021-02-15 12:31:05: Combining simulation data
#> * 2021-02-15 12:31:05: Aggregating across simulations
#> * 2021-02-15 12:31:05: Loading games data
#> * 2021-02-15 12:31:06: Beginning simulation of 500 seasons in 8 rounds
#> * 2021-02-15 12:31:33: Combining simulation data
#> * 2021-02-15 12:31:35: Aggregating across simulations
#> * 2021-02-15 12:31:35: Loading games data
#> * 2021-02-15 12:31:36: Beginning simulation of 500 seasons in 8 rounds
#> * 2021-02-15 12:32:01: Combining simulation data
#> * 2021-02-15 12:32:03: Aggregating across simulations
#> * 2021-02-15 12:32:03: Loading games data
#> * 2021-02-15 12:32:03: Beginning simulation of 500 seasons in 1 round
#> * 2021-02-15 12:32:49: Combining simulation data
#> * 2021-02-15 12:32:49: Aggregating across simulations
#> * 2021-02-15 12:32:50: Loading games data
#> * 2021-02-15 12:32:50: Beginning simulation of 500 seasons in 1 round
#> * 2021-02-15 12:33:34: Combining simulation data
#> * 2021-02-15 12:33:35: Aggregating across simulations
#> * 2021-02-15 12:33:35: Loading games data
#> * 2021-02-15 12:33:35: Beginning simulation of 500 seasons in 1 round
#> * 2021-02-15 12:34:23: Combining simulation data
#> * 2021-02-15 12:34:24: Aggregating across simulations
#> * 2021-02-15 12:34:24: Loading games data
#> * 2021-02-15 12:34:24: Beginning simulation of 500 seasons in 8 rounds
#> * 2021-02-15 12:34:51: Combining simulation data
#> * 2021-02-15 12:34:52: Aggregating across simulations
mbm
#> Unit: seconds
#>           expr      min       lq     mean   median       uq      max neval
#>   single_round 45.22389 45.96561 46.67147 46.27906 46.79665 49.09214     5
#>  quarter_cores 30.50848 30.52964 31.16637 31.25071 31.25375 32.28927     5
#>     half_cores 26.83822 27.78193 29.05832 28.29483 29.06808 33.30856     5
#>     full_cores 27.30666 28.36706 28.67068 28.48463 28.99148 30.20356     5
ggplot2::autoplot(mbm)
```
![grafik](https://user-images.githubusercontent.com/38586519/107942827-17c7b280-6f8c-11eb-8263-75eb6c16aecd.png)

**Comment by mrcaseb** [comment]
I'll close this as I believe we are done here
